save_dir: workspace/9652_effcient_lite0_ghost_pan_512_288
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite0
      out_stages: [ 2,4,6 ]
      activation: ReLU6
      # last_channel: 512
    fpn:
      name: GhostPAN
      in_channels: [ 40, 112, 320 ]
      out_channels: 96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: ReLU6
      upsample_cfg:
        scale_factor : 2
#        mode : "nearest"
        mode : "bilinear"
        align_corners : False
    head:
      name: NanoDetPlusHead
      num_classes: 3
      input_channel: 96
      feat_channels: 96
      stacked_convs: 1
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: ReLU6
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 3
      input_channel: 192
      feat_channels: 192
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
data:
  train1:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat_all/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat_all/cvat_all_COCO.json
    input_size: [512,288] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]

  val:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/testdata_set/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/testdata_set/testdata_set_COCO.json
    input_size: [512,288] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  # val1:
  #   name: CocoDataset
  #   img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat1/327/images
  #   ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat1/327/327_COCO.json
  #   input_size: [ 512,256 ] #[w,h]
  #   keep_ratio: False
  #   pipeline:
  #     normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
device:
  gpu_ids: [0]
  workers_per_gpu: 4
  batchsize_per_gpu: 16
schedule:
  # resume: True
#    load_model: /media/tclwh2/facepro/zhangdi/nanodet/workspace/effcient_lite0_ghost_pan_512_288_Nearest/model_best/model_best.ckpt
  optimizer:
    name: AdamW
    lr: 0.0005
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 150
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 150
    eta_min: 0.00005
  val_intervals: 2
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 50

class_names: ['hand', 'person', 'face']
