save_dir: workspace/effcient_lite0_ghost_pan_512_288_3head
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite0
      out_stages: [ 4,6 ]
      activation: ReLU6
      # last_channel: 512
    fpn:
      name: GhostPAN
      in_channels: [ 112, 320 ]
      out_channels: 96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: ReLU6
      upsample_cfg:
        scale_factor : 2
        mode : "bilinear"
        align_corners : False
    head:
      name: NanoDetPlusHead
      num_classes: 3
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      kernel_size: 5
      strides: [16, 32, 64]
      activation: ReLU6
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 3
      input_channel: 192
      feat_channels: 192
      stacked_convs: 4
      strides: [16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
data:
  train1:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat_all/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat_all/cvat_all_COCO.json
    input_size: [512,288] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train2:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_CROSS_FACE_2022018/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_CROSS_FACE_2022018/LX_HAND_CROSS_FACE_2022018_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train3:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_CROSS_FACE_2022022/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_CROSS_FACE_2022022/LX_HAND_CROSS_FACE_2022022_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train4:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_CROSS_FACE_20220304/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_CROSS_FACE_20220304/LX_HAND_CROSS_FACE_20220304_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train5:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_JINJULI_WUZHI_AND_WOQUAN_20220311/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LX_HAND_JINJULI_WUZHI_AND_WOQUAN_20220311/LX_HAND_JINJULI_WUZHI_AND_WOQUAN_20220311_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ]]
  train6:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/C3_DIANZAN_20220311/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/C3_DIANZAN_20220311/C3_DIANZAN_20220311_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train7:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/miss_all/heng_image
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/miss_all/heng_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train8:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/dianzan_data_1_data_2_data_3/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/dianzan_data_1_data_2_data_3/dianzan_data_1_data_2_data_3_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train9:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/blackmen_high_weak_light/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/blackmen_high_weak_light/blackmen_high_weak_light_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train10:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/combine_all/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/combine_all/combine_all_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train11:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/miss_all/shu_image
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/miss_all/shu_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train12:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/miss_all/square_image
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/miss_all/square_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train13:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/woquan0423/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/woquan0423/woquan0423_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train14:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/woquan_0417_bucong/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/woquan_0417_bucong/woquan_0417_bucong_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train15:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LK_WOQUAN_0616_anguang_part1_987/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LK_WOQUAN_0616_anguang_part1_987/LK_WOQUAN_0616_anguang_part1_987_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train16:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LK_WOQUAN_0616_liangguang_part1_1239/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/SZ_DATA/LK_WOQUAN_0616_liangguang_part1_1239/LK_WOQUAN_0616_liangguang_part1_1239_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  train17:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/woquan_buchong/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/woquan_buchong/woquan_buchong_COCO.json
    input_size: [ 512,288 ] #[w,h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [ 0.6, 1.4 ]
      stretch: [ [ 0.8, 1.2 ], [ 0.8, 1.2 ] ]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [ 0.6, 1.4 ]
      saturation: [ 0.5, 1.2 ]
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  val:
    name: CocoDataset
    img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/testdata_set/images
    ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/testdata_set/testdata_set_COCO.json
    input_size: [512,288] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
  # val1:
  #   name: CocoDataset
  #   img_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat1/327/images
  #   ann_path: /media/tclwh2/facepro/zcc/datasets/detection_datasets/cvat1/327/327_COCO.json
  #   input_size: [ 512,256 ] #[w,h]
  #   keep_ratio: False
  #   pipeline:
  #     normalize: [ [ 0.0, 0.0, 0.0 ], [ 255.0,255.0,255.0 ] ]
device:
  gpu_ids: [0,1,4,5,6]
  workers_per_gpu: 4
  batchsize_per_gpu: 16
schedule:
  # resume: True
  # load_model: /media/tclwh2/facepro/zhangdi/NanodetPlus/workspace/mv05_zcc_normal_pan_512_288_head_data14/model_best/model_best.ckpt
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 300
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  val_intervals: 10
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 50

class_names: ['hand', 'person', 'face']
